name: drag_and_drop_flutter
description: Support native drag and drop of text, files and directories in Flutter.
version: 0.3.0
homepage: https://github.com/Jjagg/drag_and_drop_flutter/tree/main/packages/drag_and_drop_flutter
repository: https://github.com/Jjagg/drag_and_drop_flutter/tree/main/packages/drag_and_drop_flutter
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        dartPluginClass: NullDragAndDropPlatform
      ios:
        dartPluginClass: NullDragAndDropPlatform
      web:
        default_package: drag_and_drop_flutter_web

dependencies:
  cross_file: ^0.3.4+1
#  drag_and_drop_flutter_platform_interface: ^0.2.1
#  drag_and_drop_flutter_web: ^0.2.1
  drag_and_drop_flutter_platform_interface:
    path: ../drag_and_drop_flutter_platform_interface
  drag_and_drop_flutter_web:
    path: ../drag_and_drop_flutter_web
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
